### ISSUE TITLE
Error when using a custom question json file

### ISSUE THREAD

**Issue by scotchneat** [anduong96/Eff#1]
When I try to use a different question list besides [this one](https:/gist.githubusercontent.com/anduong96/d64f1bbbef594c463b7f903dc978aa6d/raw/98b1dfc42eacbaab8dd9e266637af8bdfea1981d/Oracle12cNotes.json), I get the following error.

```
VM31:1 Mixed Content: The page at 'https://anduong96.github.io/Eff/take/?url=undefined&timeLimit=7200&testLength=2' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://undefined/'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ VM31:1
```

I download the code to try locally but no question json works.

Also of note, when I provide a valid json url on the home page and click `Check Link!`, it does download the json content and lists the correct number of questions.

After I'm done with my class, I'll see if I can spend some time to look at this and submit a PR.

**Comment by scotchneat** [comment]
I was able to set the value of `url` to my custom questions json in the query params manually and it would work. There must be something up with the `Take` button not setting the url properly.

**Comment by anduong96** [comment]
Can you provide the link that you tried?

**Comment by anduong96** [comment]
The json link

**Comment by scotchneat** [comment]
https://gist.githubusercontent.com/scotchneat/3bcff723696442122f4bf430b80ccf51/raw/68fb4b5b3d0812da01e0acf6d7898367c298d844/eff-sample.json

This same link works if you manually build the url to take the test:
https://anduong96.github.io/Eff/take/?url=https://gist.githubusercontent.com/scotchneat/3bcff723696442122f4bf430b80ccf51/raw/68fb4b5b3d0812da01e0acf6d7898367c298d844/eff-sample.json&timeLimit=1200&testLength=3

**Comment by anduong96** [comment]
Fixed here: https://github.com/anduong96/Eff/commit/68ff95509181c3419396dff7fb363bf94b3039a8#diff-6024c4248b37f74d5a3459c229235579R52


I was using the wrong url variable
